SCREEN_WIDTH:int = 1280
SCREEN_HEIGHT:int = 720

ASTEROID_MIN_RADIUS:float = 20
ASTEROID_KINDS: float = 3
ASTEROID_SPAWN_RATE: float = 0.8  # seconds
ASTEROID_MAX_RADIUS: float = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS:float = 20
PLAYER_TURN_SPEED: float = 300
PLAYER_SPEED: float = 200
PLAYER_SHOOT_COOLDOWN: float = 0.3

SHOT_RADIUS: float = 5
PLAYER_SHOOT_SPEED: float = 500